import {
  Activity,
  BadgeCheck,
  Bell,
  Box,
  Calendar,
  CheckSquare,
  ClipboardList,
  Clock,
  Download,
  Droplet,
  Factory,
  FileText,
  Flame,
  Fuel,
  Gauge,
  Globe,
  Handshake,
  History,
  Inbox,
  Layers,
  LineChart,
  List,
  Map as MapIcon,
  Package,
  PieChart,
  Search,
  Settings,
  Shield,
  Siren,
  SignalHigh,
  SlidersHorizontal,
  Target,
  TrendingDown,
  Truck,
  Users,
  Waves,
  Wind,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  "badge-check": BadgeCheck,
  bell: Bell,
  calendar: Calendar,
  chart: PieChart,
  "chart-line": LineChart,
  "check-square": CheckSquare,
  clipboard: ClipboardList,
  clock: Clock,
  cube: Box,
  download: Download,
  droplet: Droplet,
  factory: Factory,
  "file-text": FileText,
  flame: Flame,
  fuel: Fuel,
  gauge: Gauge,
  globe: Globe,
  handshake: Handshake,
  history: History,
  inbox: Inbox,
  layers: Layers,
  list: List,
  map: MapIcon,
  package: Package,
  search: Search,
  settings: Settings,
  shield: Shield,
  signal: SignalHigh,
  siren: Siren,
  sliders: SlidersHorizontal,
  target: Target,
  "trending-down": TrendingDown,
  truck: Truck,
  users: Users,
  waveform: Waves,
  wind: Wind,
  zap: Zap,
};

export function ModuleIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICONS[name] ?? Activity;
  return <Icon className={className} strokeWidth={1.6} aria-hidden />;
}
